---
kind: pipeline
type: docker
name: default

steps:
- name: npm install
  image: node:alpine
  commands:
  - npm i --registry https://registry.npm.taobao.org

- name: test
image: node:alpine
commands:
- npm run test



...